//! Common functionality used by other Training
//! Assistant systems.
use std::result;

/// API for interacting with the SQL database.
pub mod db;

#[cfg(feature = "bevy")]
pub mod bevy;

#[cfg(feature = "dolmen")]
pub mod dolmen;

/// Various types of errors that can be generated by a `Context`.
#[derive(Debug, Default)]
pub struct Error {
    message: Option<String>,
}

impl Error {
    /// Creates a new `Error` with a message.
    ///
    /// * `message` - The message to display for this error.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: Some(message.into()),
        }
    }

    /// Gets the message from an `Error`, or `None` if it doesn't have one.
    pub fn message(&self) -> &Option<String> {
        &self.message
    }
}

impl std::error::Error for Error {}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self.message)
    }
}

/// A result type for errors generated by the
/// framework.
pub type Result<T, E = Error> = result::Result<T, E>;

impl From<rusqlite::Error> for Error {
    fn from(e: rusqlite::Error) -> Self {
        Error::new(format!("database error: {}", e.to_string()))
    }
}

impl From<std::io::Error> for Error {
    fn from(e: std::io::Error) -> Self {
        Error::new(format!("file error: {}", e.to_string()))
    }
}

/// Common imports for working with the `framework`
/// crate.
pub mod prelude {
    pub use crate::db::{DbConnection, FieldTypeInfo, RowId, TableConfig, TableField, TableRow};
    pub use macros::TableRow;
}
